
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'TAG_CLOSE TAG_OPEN TAG_SELF_CLOSE TEXThtml : elementselements : elements element\n                | elementelement : TAG_OPEN elements TAG_CLOSE\n               | TAG_SELF_CLOSE\n               | TEXT'
    
_lr_action_items = {'TAG_OPEN':([0,2,3,4,5,6,7,8,9,],[4,4,-3,4,-5,-6,-2,4,-4,]),'TAG_SELF_CLOSE':([0,2,3,4,5,6,7,8,9,],[5,5,-3,5,-5,-6,-2,5,-4,]),'TEXT':([0,2,3,4,5,6,7,8,9,],[6,6,-3,6,-5,-6,-2,6,-4,]),'$end':([1,2,3,5,6,7,9,],[0,-1,-3,-5,-6,-2,-4,]),'TAG_CLOSE':([3,5,6,7,8,9,],[-3,-5,-6,-2,9,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'html':([0,],[1,]),'elements':([0,4,],[2,8,]),'element':([0,2,4,8,],[3,7,3,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> html","S'",1,None,None,None),
  ('html -> elements','html',1,'p_html','app.py',36),
  ('elements -> elements element','elements',2,'p_elements','app.py',40),
  ('elements -> element','elements',1,'p_elements','app.py',41),
  ('element -> TAG_OPEN elements TAG_CLOSE','element',3,'p_element','app.py',45),
  ('element -> TAG_SELF_CLOSE','element',1,'p_element','app.py',46),
  ('element -> TEXT','element',1,'p_element','app.py',47),
]
